# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f07a7b8e1e808cb9e37ed11273955b63"
name = "crockettcoffee-google"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
# App Proxy для Google Reviews widget
# URL будет: shop.myshopify.com/apps/google-reviews/*
url = "https://example.com/proxy"
subpath = "google-reviews"
prefix = "apps"
