# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

api_version = "2025-01"

[[extensions]]

uid = "92f3f6e2-1c4b-b7e5-4ab2-2e7d26238dd6a5e8c98c"

type = "ui_extension"
name = "thank-you-google-reviews"
handle = "thank-you-google-reviews"

[[extensions.targeting]]
module = "./src/ThankYou.jsx"
target = "purchase.thank-you.block.render"
